version: '3.8'

services:
  # Service 1 : Le serveur MCP pour l'API data.inclusion
  mcp_server:
    build: .
    command: python -m src.mcp.server
    env_file:
      - .env
    ports:
      - "8000:8000" # Mappe le port 8000 de l'hôte au conteneur
    volumes:
      - ./src:/app/src # Synchronise le code pour le développement
    networks:
      - app-network

  # Service 2 : Le serveur Agent qui communique avec le frontend et le MCP
  agent_server:
    build: .
    command: python main.py
    env_file:
      - .env
    ports:
      - "8001:8001" # Mappe le port 8001 de l'hôte au conteneur
    volumes:
      - ./src:/app/src
    networks:
      - app-network
    depends_on:
      - mcp_server # S'assure que le MCP est démarré avant l'agent

networks:
  app-network:
    driver: bridge 